import json
import re
import sys
import zipfile
from pathlib import Path
from typing import Dict


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from src.pipeline import ContentPipeline

DESKTOP = Path.home() / "Desktop"
SAMPLE_ZIP = DESKTOP / "drive-download-20260513T174643Z-3-001.zip"
WORK_DIR = ROOT / "data" / "sample_docs"
OUT_DIR = ROOT / "outputs"


def infer_page_type(file_name: str) -> str:
    lowered = file_name.lower()
    if "marketing" in lowered or "data science" in lowered:
        return "specialization"
    if "mba program" in lowered or "online mba" in lowered:
        return "course"
    return "university"


def slugify(value: str) -> str:
    value = re.sub(r"\.docx$", "", value, flags=re.IGNORECASE)
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def ensure_samples() -> list[Path]:
    WORK_DIR.mkdir(parents=True, exist_ok=True)
    if SAMPLE_ZIP.exists():
        try:
            with zipfile.ZipFile(SAMPLE_ZIP) as archive:
                archive.extractall(WORK_DIR)
        except PermissionError:
            print(f"Skipping zip extraction due to permissions. Checking if files exist in {WORK_DIR}...")
    return sorted(WORK_DIR.glob("*.docx"))


def report_to_dict(report) -> Dict:
    payload = {
        field_name: field.value
        for field_name, field in report.extracted_fields.items()
        if getattr(field, "value", None)
    }
    warnings = [warning.model_dump() for warning in report.warnings]
    mapped = sum(1 for field in report.extracted_fields.values() if getattr(field, "value", None))
    return {
        "document_name": report.document_name,
        "page_type": report.page_type,
        "quality_score": report.quality_score,
        "mapped_fields": mapped,
        "total_fields": len(report.extracted_fields),
        "is_publishable": report.is_publishable,
        "warnings": warnings,
        "fields_needing_review": report.fields_needing_review,
        "unmapped_sections": report.unmapped_sections,
        "payload": payload,
    }


def main() -> None:
    docs = ensure_samples()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    pipeline = ContentPipeline()
    summaries = []

    for doc in docs:
        page_type = infer_page_type(doc.name)
        report = pipeline.process_file(str(doc), doc.name, page_type)
        result = report_to_dict(report)
        summaries.append(result)
        output_path = OUT_DIR / f"{slugify(doc.name)}-{page_type}-payload.json"
        output_path.write_text(json.dumps(result["payload"], indent=2, ensure_ascii=False))

    summary_path = OUT_DIR / "validation-summary.json"
    summary_path.write_text(json.dumps(summaries, indent=2, ensure_ascii=False))

    markdown = [
        "# DegreeBaba MVP Test Results",
        "",
        "Generated by `scripts/generate_test_artifacts.py`.",
        "",
        "## Coverage Note",
        "",
        "The supplied archive contains three DOCX files. The task brief asks for two files per page type, so this script processes every supplied DOCX and is ready to process additional files when they are placed in `data/sample_docs/`.",
        "",
        "## Results",
        "",
        "| Document | Page Type | Score | Mapped / Total | Errors | Warnings |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for result in summaries:
        errors = sum(1 for warning in result["warnings"] if warning["severity"] == "error")
        warnings = sum(1 for warning in result["warnings"] if warning["severity"] != "error")
        markdown.append(
            f"| {result['document_name']} | {result['page_type']} | {result['quality_score']} | "
            f"{result['mapped_fields']} / {result['total_fields']} | {errors} | {warnings} |"
        )

    markdown.extend(
        [
            "",
            "## How To Reproduce",
            "",
            "```bash",
            ".venv/bin/python scripts/generate_test_artifacts.py",
            "```",
        ]
    )
    (OUT_DIR / "validation-report.md").write_text("\n".join(markdown))
    print(f"Wrote {len(summaries)} test result(s) to {OUT_DIR}")


if __name__ == "__main__":
    main()
